package ru.ani.subscription.management.service.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClientSubscriptionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientSubscriptionAllPropertiesEquals(ClientSubscription expected, ClientSubscription actual) {
        assertClientSubscriptionAutoGeneratedPropertiesEquals(expected, actual);
        assertClientSubscriptionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientSubscriptionAllUpdatablePropertiesEquals(ClientSubscription expected, ClientSubscription actual) {
        assertClientSubscriptionUpdatableFieldsEquals(expected, actual);
        assertClientSubscriptionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientSubscriptionAutoGeneratedPropertiesEquals(ClientSubscription expected, ClientSubscription actual) {
        assertThat(actual)
            .as("Verify ClientSubscription auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientSubscriptionUpdatableFieldsEquals(ClientSubscription expected, ClientSubscription actual) {
        assertThat(actual)
            .as("Verify ClientSubscription relevant properties")
            .satisfies(a -> assertThat(a.getStartDttm()).as("check startDttm").isEqualTo(expected.getStartDttm()))
            .satisfies(a -> assertThat(a.getEndDttm()).as("check endDttm").isEqualTo(expected.getEndDttm()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClientSubscriptionUpdatableRelationshipsEquals(ClientSubscription expected, ClientSubscription actual) {
        assertThat(actual)
            .as("Verify ClientSubscription relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()))
            .satisfies(a ->
                assertThat(a.getSubscriptionDetails()).as("check subscriptionDetails").isEqualTo(expected.getSubscriptionDetails())
            );
    }
}
