package ru.ani.subscription.management.service.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExternalUserDaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalUserDaoAllPropertiesEquals(ExternalUserDao expected, ExternalUserDao actual) {
        assertExternalUserDaoAutoGeneratedPropertiesEquals(expected, actual);
        assertExternalUserDaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalUserDaoAllUpdatablePropertiesEquals(ExternalUserDao expected, ExternalUserDao actual) {
        assertExternalUserDaoUpdatableFieldsEquals(expected, actual);
        assertExternalUserDaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalUserDaoAutoGeneratedPropertiesEquals(ExternalUserDao expected, ExternalUserDao actual) {
        assertThat(actual)
            .as("Verify ExternalUserDao auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalUserDaoUpdatableFieldsEquals(ExternalUserDao expected, ExternalUserDao actual) {
        assertThat(actual)
            .as("Verify ExternalUserDao relevant properties")
            .satisfies(a -> assertThat(a.getExternalUserId()).as("check externalUserId").isEqualTo(expected.getExternalUserId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExternalUserDaoUpdatableRelationshipsEquals(ExternalUserDao expected, ExternalUserDao actual) {
        // empty method
    }
}
