package ru.ani.subscription.management.service.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PaymentSystemDaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentSystemDaoAllPropertiesEquals(PaymentSystemDao expected, PaymentSystemDao actual) {
        assertPaymentSystemDaoAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentSystemDaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentSystemDaoAllUpdatablePropertiesEquals(PaymentSystemDao expected, PaymentSystemDao actual) {
        assertPaymentSystemDaoUpdatableFieldsEquals(expected, actual);
        assertPaymentSystemDaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentSystemDaoAutoGeneratedPropertiesEquals(PaymentSystemDao expected, PaymentSystemDao actual) {
        assertThat(actual)
            .as("Verify PaymentSystemDao auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentSystemDaoUpdatableFieldsEquals(PaymentSystemDao expected, PaymentSystemDao actual) {
        assertThat(actual)
            .as("Verify PaymentSystemDao relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentSystemDaoUpdatableRelationshipsEquals(PaymentSystemDao expected, PaymentSystemDao actual) {
        // empty method
    }
}
