package ru.ani.subscription.management.service.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static ru.ani.subscription.management.service.domain.AssertUtils.bigDecimalCompareTo;

public class ReferralProgramAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralProgramAllPropertiesEquals(ReferralProgram expected, ReferralProgram actual) {
        assertReferralProgramAutoGeneratedPropertiesEquals(expected, actual);
        assertReferralProgramAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralProgramAllUpdatablePropertiesEquals(ReferralProgram expected, ReferralProgram actual) {
        assertReferralProgramUpdatableFieldsEquals(expected, actual);
        assertReferralProgramUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralProgramAutoGeneratedPropertiesEquals(ReferralProgram expected, ReferralProgram actual) {
        assertThat(actual)
            .as("Verify ReferralProgram auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralProgramUpdatableFieldsEquals(ReferralProgram expected, ReferralProgram actual) {
        assertThat(actual)
            .as("Verify ReferralProgram relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getReferralCode()).as("check referralCode").isEqualTo(expected.getReferralCode()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getStartDttm()).as("check startDttm").isEqualTo(expected.getStartDttm()))
            .satisfies(a -> assertThat(a.getEndDttm()).as("check endDttm").isEqualTo(expected.getEndDttm()))
            .satisfies(a ->
                assertThat(a.getRewardAmount())
                    .as("check rewardAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRewardAmount())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertReferralProgramUpdatableRelationshipsEquals(ReferralProgram expected, ReferralProgram actual) {
        assertThat(actual)
            .as("Verify ReferralProgram relationships")
            .satisfies(a -> assertThat(a.getSourceApplication()).as("check sourceApplication").isEqualTo(expected.getSourceApplication()));
    }
}
