package ru.aniscan.subscription.management.service.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SourceApplicationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceApplicationAllPropertiesEquals(SourceApplication expected, SourceApplication actual) {
        assertSourceApplicationAutoGeneratedPropertiesEquals(expected, actual);
        assertSourceApplicationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceApplicationAllUpdatablePropertiesEquals(SourceApplication expected, SourceApplication actual) {
        assertSourceApplicationUpdatableFieldsEquals(expected, actual);
        assertSourceApplicationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceApplicationAutoGeneratedPropertiesEquals(SourceApplication expected, SourceApplication actual) {
        assertThat(expected)
            .as("Verify SourceApplication auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceApplicationUpdatableFieldsEquals(SourceApplication expected, SourceApplication actual) {
        assertThat(expected)
            .as("Verify SourceApplication relevant properties")
            .satisfies(e -> assertThat(e.getApplicationName()).as("check applicationName").isEqualTo(actual.getApplicationName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSourceApplicationUpdatableRelationshipsEquals(SourceApplication expected, SourceApplication actual) {
        assertThat(expected)
            .as("Verify SourceApplication relationships")
            .satisfies(e -> assertThat(e.getPaymentSystems()).as("check paymentSystems").isEqualTo(actual.getPaymentSystems()));
    }
}
